# Generated by Django 5.0.6 on 2024-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="category",
            field=models.CharField(
                choices=[
                    ("career", "진로"),
                    ("health", "건강"),
                    ("relationships", "인간 관계"),
                    ("money", "돈"),
                    ("goals", "목표"),
                    ("academics", "학업/성적"),
                    ("others", "기타"),
                ],
                default="others",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wish",
            name="is_confirm",
            field=models.CharField(
                choices=[("pending", "보류"), ("approved", "승인"), ("rejected", "거절")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
