# Generated by Django 5.0.6 on 2024-08-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0002_wish_category_wish_is_confirm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="is_confirm",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
