# Generated by Django 5.0.6 on 2024-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0003_alter_wish_is_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wish",
            name="is_confirm",
            field=models.CharField(
                choices=[("pending", "보류"), ("approved", "승인"), ("rejected", "거절")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
